# Actions
ACTIONS = [START, SELECTING_TRACK_ACTION, SELECTING_ENGINEERING, SELECTING_DATA_SCIENCE,
           SELECTING_MANAGEMENT] \
    = list(map(str, range(5)))

# Different users
IAM_NEW_USER, IAM_OLD_USER = map(str, range(5, 7))

SELECT_TRACK_FROM_START = str(7)

TRACKS_SET = [TRACK_ENGINEERING, TRACK_DS, TRACK_MANAGEMENT, TRACK_MARKETING,
              TRACK_QA, SELECT_TRACK_NEXT, RETURN_TO_SELECT_TRACK] \
    = list(map(str, range(8, 15)))

TRACK_ENGINEERING_SET = [ENGIN_JAVA, ENGIN_PY, ENGIN_CSH, ENGIN_IOS, ENGIN_ANDROID, ENGIN_CPP,
                         ENGIN_GO, ENGIN_RUBY, ENGIN_PHP, ENGIN_JS_FRONT, ENGIN_JS_BACK,
                         ENGIN_DEVOPS] \
    = list(map(str, range(15, 27)))

TRACK_DS_SET = [DS_ANALYST, DS_ENGINEER, DS_SIMP_ANALYST, DS_ML_ENGINEER, DS_ML_RESEARCHER] \
    = list(map(str, range(27, 32)))

TRACK_MANAGEMENT_SET = [MANAGEMENT_PRODUCT, MANAGEMENT_PROJECT, MANAGEMENT_TECH, MANAGEMENT_AGILE,
                        MANAGEMENT_HR] \
    = list(map(str, range(32, 37)))

TRACK_SIMPLE_SET = [TRACK_DESIGN] = list(map(str, range(37, 38)))
